services:
  web:
    image: nginx:latest
    container_name: nginx-products
    ports: 
      - "8080:80"
    volumes:
      - .:/var/www/public
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: .
    container_name: php-fpm-products
    working_dir: /var/www/
    volumes:
      - .:/var/www/public
    links: 
      - db
  db:
    image: mysql:latest
    container_name: mysql-products
    ports:
    - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 85:80
    environment:
      - PMA_ARBITRARY=1